services:
  - type: web
    name: noise-monitoring-app
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_WIDE_VIEW
        value: wide_view
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
